apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envoy-proxy.fullname" . }}-config
  labels:
    {{- include "envoy-proxy.labels" . | nindent 4 }}
data:
  envoy.yaml: {{ .Files.Get "assets/envoy.yaml" | quote }}
  cert.pem: {{ .Files.Get "assets/tls/cert.pem" | quote }}
  key.pem: {{ .Files.Get "assets/tls/key.pem" | quote }}
binaryData:
  proto.pb: {{ .Files.Get "assets/proto.pb" | b64enc }}
