{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "envoy-proxy.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "envoy-proxy.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.common.infra.tls.enabled }}
    cert-manager.io/issuer: {{ .Values.common.infra.tls.issuer }} 
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
  {{- range $p := $.Values.ingress.paths }}
          - path: {{ tpl $p $ }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  name: http
  {{- end -}}
  {{- end -}}
  {{- else }}
    - http:
        paths:
  {{- range $p := .Values.ingress.paths }}
          - path: {{ tpl $p $ }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  name: http
  {{- end -}}
  {{- end -}}  
  {{- end }}
