{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "seq.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "seq.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.common.infra.tls.enabled }}
    cert-manager.io/issuer: {{ .Values.common.infra.tls.issuer }} 
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.host }}
      http:
        paths:
          - path: {{ $host.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  name: {{ $host.name }}
  {{- end -}}
  {{- end -}}  
  {{- end }}
