apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sql-data.fullname" . }}
  labels:
    {{- include "sql-data.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sql-data.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sql-data.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_PID
            value: {{ .Values.common.infra.sqlsrv.pid }}
          - name: MSSQL_SA_PASSWORD
            value: {{ .Values.common.infra.sqlsrv.pwd }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}