version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  sql-data:
    image: mcr.microsoft.com/mssql/server:2017-latest 

  redis-data:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  envoy-proxy:
    image: envoyproxy/envoy:v1.16-latest

  file-service:
    image: ${REGISTRY:-harta}/file.service:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/File/File.API/Dockerfile
    depends_on:
      - redis-data
      - rabbitmq

  ordering-service:
    image: ${REGISTRY:-harta}/ordering-service:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - sql-data
      - rabbitmq

  webstatus:
    image: ${REGISTRY:-harta}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Client/WebStatus/Dockerfile
