version: '3.4'

services:
  sql-test:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  redis-test:
    ports:
      - "6379:6379"

  rabbitmq-test:
    ports:
      - "15672:15672"
      - "5672:5672"

  envoy-proxy-test:
    environment:
      - ENVOY_UID=0
    ports:
      - "8080:80"
      - "8443:443"
      - "8001:8001"
    volumes: 
      - ./Proto/proto.pb:/etc/proto/proto.pb
      - ./ApiGateways/Envoy/test/envoy.yaml:/etc/envoy/envoy.yaml
      - ./ApiGateways/Envoy/ssl:/etc/ssl/certs

  file-service-test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ORCHESTRATOR_TYPE=${ORCHESTRATOR_TYPE}
      - OrderingUrl=http://ordering-service-test:5001
      - ConnectionStrings__IntegrationEventConnStr=redis-test
      - ConnectionStrings__MappingSvcConnStr=Data Source=host.docker.internal;Initial Catalog=RPA-misc;User ID=sa;Password=p@ssw0rd;
      - EventBusConnection=rabbitmq-test
      - SourceFolder=/media/test
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - UseLoadTest=${USE_LOADTEST:-False}
    volumes: 
      - /c/Users/hafiz.roslan.HARTALEGA/Documents/RPA/Projects/HartaRPA/tests:/media/test
    ports:
      - "5111:80"
  
  ordering-service-test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ORCHESTRATOR_TYPE=${ORCHESTRATOR_TYPE}
      - ConnectionString=Data Source=host.docker.internal;Initial Catalog=Harta.Services.OrderingDb;User ID=sa;Password=p@ssw0rd;
      - EventBusConnection=rabbitmq-test
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5112:80"
      - "5113:5001"      
