version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  envoy-proxy:
    image: envoyproxy/envoy:v1.16-latest

  file-service:
    image: ${REGISTRY:-harta}/file.service:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/File/File.API/Dockerfile
    depends_on:
      - redis
      - rabbitmq

  # ordering.api:
  #   image: ${DOCKER_REGISTRY-}orderingapi
  #   build:
  #     context: .
  #     dockerfile: Services/Ordering/Ordering.API/Dockerfile