replicaCount: 1

image:
  repository: microsoft/mssql-server-linux
  pullPolicy: IfNotPresent
  tag: 2017-CU7

service:
  type: ClusterIP
  port: 1433

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
